export const batmanResponses = {
  Batman: {
    Title: 'Batman',
    Year: '1989',
    Rated: 'PG-13',
    Released: '23 Jun 1989',
    Runtime: '126 min',
    Genre: 'Action, Adventure',
    Director: 'Tim Burton',
    Writer:
      'Bob Kane (Batman characters), Sam Hamm (story), Sam Hamm (screenplay), Warren Skaaren (screenplay)',
    Actors: 'Michael Keaton, Jack Nicholson, Kim Basinger, Robert Wuhl',
    Plot:
      'The Dark Knight of Gotham City begins his war on crime with his first major enemy being Jack Napier, a criminal who becomes the clownishly homicidal Joker.',
    Language: 'English, French, Spanish',
    Country: 'USA, UK',
    Awards: 'Won 1 Oscar. Another 7 wins & 26 nominations.',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.5/10' },
      { Source: 'Rotten Tomatoes', Value: '71%' },
      { Source: 'Metacritic', Value: '69/100' },
    ],
    Metascore: '69',
    imdbRating: '7.5',
    imdbVotes: '339,039',
    imdbID: 'tt0096895',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$251,348,343',
    Production:
      'Warner Brothers, Guber-Peters Company, PolyGram Filmed Entertainment',
    Website: 'N/A',
    Response: 'True',
  },

  'Batman Returns': {
    Title: 'Batman Returns',
    Year: '1992',
    Rated: 'PG-13',
    Released: '19 Jun 1992',
    Runtime: '126 min',
    Genre: 'Action, Crime, Fantasy',
    Director: 'Tim Burton',
    Writer:
      'Bob Kane (Batman characters), Daniel Waters (story), Sam Hamm (story), Daniel Waters (screenplay)',
    Actors:
      'Michael Keaton, Danny DeVito, Michelle Pfeiffer, Christopher Walken',
    Plot:
      'While Batman deals with a deformed man calling himself the Penguin wreaking havoc across Gotham with the help of a cruel businessman, a female employee of the latter becomes the Catwoman with her own vendetta.',
    Language: 'English',
    Country: 'USA, UK',
    Awards: 'Nominated for 2 Oscars. Another 2 wins & 27 nominations.',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.0/10' },
      { Source: 'Rotten Tomatoes', Value: '80%' },
      { Source: 'Metacritic', Value: '68/100' },
    ],
    Metascore: '68',
    imdbRating: '7.0',
    imdbVotes: '275,205',
    imdbID: 'tt0103776',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$162,902,340',
    Production: 'Warner Brothers',
    Website: 'N/A',
    Response: 'True',
  },
  'Batman Forever': {
    Title: 'Batman Forever',
    Year: '1995',
    Rated: 'PG-13',
    Released: '16 Jun 1995',
    Runtime: '121 min',
    Genre: 'Action, Adventure',
    Director: 'Joel Schumacher',
    Writer:
      'Bob Kane (characters), Lee Batchler (story), Janet Scott Batchler (story), Lee Batchler (screenplay), Janet Scott Batchler (screenplay), Akiva Goldsman (screenplay)',
    Actors: 'Val Kilmer, Tommy Lee Jones, Jim Carrey, Nicole Kidman',
    Plot:
      'Batman must battle former district attorney Harvey Dent, who is now Two-Face and Edward Nygma, The Riddler with help from an amorous psychologist and a young circus acrobat who becomes his sidekick, Robin.',
    Language: 'English',
    Country: 'USA, UK',
    Awards: 'Nominated for 3 Oscars. Another 10 wins & 23 nominations.',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNDdjYmFiYWEtYzBhZS00YTZkLWFlODgtY2I5MDE0NzZmMDljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '5.4/10' },
      { Source: 'Rotten Tomatoes', Value: '39%' },
      { Source: 'Metacritic', Value: '51/100' },
    ],
    Metascore: '51',
    imdbRating: '5.4',
    imdbVotes: '235,401',
    imdbID: 'tt0112462',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$184,069,126',
    Production: 'Warner Brothers, PolyGram Filmed Entertainment',
    Website: 'N/A',
    Response: 'True',
  },
  'Batman & Robin': {
    Title: 'Batman & Robin',
    Year: '1997',
    Rated: 'PG-13',
    Released: '20 Jun 1997',
    Runtime: '125 min',
    Genre: 'Action, Sci-Fi',
    Director: 'Joel Schumacher',
    Writer: 'Bob Kane (Batman characters), Akiva Goldsman',
    Actors:
      "Arnold Schwarzenegger, George Clooney, Chris O'Donnell, Uma Thurman",
    Plot:
      'Batman and Robin try to keep their relationship together even as they must stop Mr. Freeze and Poison Ivy from freezing Gotham City.',
    Language: 'English',
    Country: 'USA, UK',
    Awards: '10 wins & 22 nominations.',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMGQ5YTM1NmMtYmIxYy00N2VmLWJhZTYtN2EwYTY3MWFhOTczXkEyXkFqcGdeQXVyNTA2NTI0MTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '3.8/10' },
      { Source: 'Rotten Tomatoes', Value: '11%' },
      { Source: 'Metacritic', Value: '28/100' },
    ],
    Metascore: '28',
    imdbRating: '3.8',
    imdbVotes: '234,660',
    imdbID: 'tt0118688',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$107,353,792',
    Production: 'Warner Bros., PolyGram Filmed Entertainment',
    Website: 'N/A',
    Response: 'True',
  },
  'Batman Begins': {
    Title: 'Batman Begins',
    Year: '2005',
    Rated: 'PG-13',
    Released: '15 Jun 2005',
    Runtime: '140 min',
    Genre: 'Action, Adventure',
    Director: 'Christopher Nolan',
    Writer:
      'Bob Kane (characters), David S. Goyer (story), Christopher Nolan (screenplay), David S. Goyer (screenplay)',
    Actors: 'Christian Bale, Michael Caine, Liam Neeson, Katie Holmes',
    Plot:
      'After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.',
    Language: 'English, Mandarin',
    Country: 'USA, UK',
    Awards: 'Nominated for 1 Oscar. Another 14 wins & 75 nominations.',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.2/10' },
      { Source: 'Rotten Tomatoes', Value: '84%' },
      { Source: 'Metacritic', Value: '70/100' },
    ],
    Metascore: '70',
    imdbRating: '8.2',
    imdbVotes: '1,306,535',
    imdbID: 'tt0372784',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$206,852,432',
    Production: 'Warner Brothers, Di Bonaventura Pictures',
    Website: 'N/A',
    Response: 'True',
  },
  'The Dark Knight': {
    Title: 'The Dark Knight',
    Year: '2008',
    Rated: 'PG-13',
    Released: '18 Jul 2008',
    Runtime: '152 min',
    Genre: 'Action, Crime, Drama, Thriller',
    Director: 'Christopher Nolan',
    Writer:
      'Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)',
    Actors: 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine',
    Plot:
      'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    Language: 'English, Mandarin',
    Country: 'USA, UK',
    Awards: 'Won 2 Oscars. Another 156 wins & 163 nominations.',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.0/10' },
      { Source: 'Rotten Tomatoes', Value: '94%' },
      { Source: 'Metacritic', Value: '84/100' },
    ],
    Metascore: '84',
    imdbRating: '9.0',
    imdbVotes: '2,308,981',
    imdbID: 'tt0468569',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$534,858,444',
    Production: 'Syncopy',
    Website: 'N/A',
    Response: 'True',
  },
};
